[FEATURE] Adding docker images
MRB-Computer-Vision/web-backend-admin pull request #1
Opened 2020-05-05 01:54 UTC by alexmaramaldo

2020-05-07 13:55 UTC, bragadennis requested changes

2020-05-07 13:55 UTC, bragadennis commented on docker/app/Dockerfile
> +COPY ./requirements_dev.txt .
Eu não entendi os dois documentos de requirements(_dev). Um é só pro ambiente de dev?

2020-05-07 13:55 UTC, bragadennis commented on docker/docker-compose.yml
> +      - "POSTGRES_PASSWORD=postgres"
A gente não consegue parametrizar isso com o .env? Pra facilitar o deploy?

2020-05-07 18:25 UTC, alexmaramaldo commented on docker/app/Dockerfile
> +COPY ./requirements_dev.txt .
Exatamente isso. A ideia é nao rodar o _dev em produção!

2020-05-07 18:26 UTC, alexmaramaldo commented on docker/docker-compose.yml
> +      - "POSTGRES_PASSWORD=postgres"
Podemos sim, so editar e jogar isso no .env!

2020-05-08 14:50 UTC, edsoncavalcanti requested changes
Adiciona o zookeeper e o kafka por favor na infra

2020-05-08 14:50 UTC, edsoncavalcanti commented on docker/docker-compose.yml
> +
Adiciona por favor o zookeeper e o kafka.

https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose.yml

2020-05-09 00:32 UTC, closed without merging